# Generated by Django 4.0.4 on 2022-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opskrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('ingredienser', models.CharField(max_length=1000)),
                ('instrukser', models.CharField(max_length=1000)),
            ],
        ),
    ]
