# Generated by Django 4.0.4 on 2022-05-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opskrifter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='opskrift',
            name='ingredienser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opskrifter.ingrediens'),
        ),
    ]
