# Generated by Django 4.0.4 on 2022-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opskrifter', '0002_ingrediens_alter_opskrift_ingredienser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opskrift',
            name='ingredienser',
        ),
        migrations.AddField(
            model_name='opskrift',
            name='ingredienser',
            field=models.ManyToManyField(to='opskrifter.ingrediens'),
        ),
    ]
